In [1]:
#question 1
import numpy as np

arr = np.array([[2,3],[4,5]])
print(arr)


[[2 3]
 [4 5]]


In [5]:
#question 2
import numpy as np

arr = np.random.randint(1, 10, size = (3, 4))
print(arr)

[[8 1 7 8]
 [7 7 9 4]
 [4 3 1 8]]


In [4]:
#question 3
import numpy as np

#numpy array filled with ones
arr_one = np.ones((3, 4))
print(arr_one)

#numpy array filled with zeros
arr_zero = np.zeros((3,4))
print("\n", arr_zero)


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [3]:
#question 4
import numpy as np

arr = np.random.randint(1, 10, size = (6,3))

print("before transpose:")
print(arr, end = '\n\n')

print("after transpose:")
print(arr.transpose())


before transpose:
[[2 8 9]
 [7 1 6]
 [1 8 9]
 [8 2 8]
 [7 9 2]
 [7 4 8]]

after transpose:
[[2 7 1 8 7 7]
 [8 1 8 2 9 4]
 [9 6 9 8 2 8]]


In [2]:
#question 5
import numpy as np

arr1 = np.random.randint(1, 10, size = (2,3))
arr2 = np.random.randint(1, 10, size = (3,4))
print(np.dot(arr1, arr2))

[[ 70  54 158 152]
 [ 52  36 134 113]]
